
services:
  quantis-backend:
    image: ${YOUR_DOCKERHUB_USER}/quantis-backend:latest
    container_name: quantis-backend
    restart: unless-stopped
    ports:
      - "4001:4001"
    environment:
      PORT: "4001"
      ARCHIVE_NEU_URL: "https://archive.neu.edu.vn"
      OLLAMA_UPSTREAM_URL: "http://host.docker.internal:8002"
      ANALYZE_PYTHON_URL: "http://quantis-python:8000"
    volumes:
      - quantis-data:/app/data
    extra_hosts:
      - "host.docker.internal:host-gateway"

  quantis-python:
    image: ${YOUR_DOCKERHUB_USER}/quantis-python:latest
    container_name: quantis-python
    restart: unless-stopped
    ports:
      - "4000:8000"
    environment:
      - PYTHONUNBUFFERED=1

volumes:
  quantis-data:
